name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: |
          npm run build:typescript
          npm run build:sass

        with:
          ACCESS_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          BRANCH: gh-pages
          FOLDER: dist

      - name: Release
        run: npm run release
        env:
            TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
